MAYA-105623 better support for USD leftHanded mesh.
Autodesk/maya-usd pull request #1139
Opened 2021-02-01 18:28 UTC by pierrebai-adsk

The  main problem is that the 'leftHanded' orientation is USD changes the interpretation of the vertices order of faces *and* the direction of generated normals.

On the other hand, the 'opposite' flag in Maya flips the faces directions, but does not flip the normals.

So the behaviour differs. To better suport USD import of externally-generated USD files, we will no longer set the 'opposite' flag when importing ledftHanded USD files. We will instead change the vertices orders to be right-handed.

Note that we will still export 'opposite' geometries from Maya as by setting the 'leftHanded' flag. This is done for two reasons: first, to keep the code change minimal, second because USD does not support different handedness for faces and normasl anyway.

2021-02-01 19:02 UTC, JGamache-autodesk requested changes
The code looks good. I am a bit unsure about algorithms that could potentially use adjacent triangles like OpenSubDiv, but if subdivided left and right handed cubes look good then things should be fine.

Can you add a unit test? There is a `\test\lib\usd\translators\testUsdImportMesh.py` that could be expanded to include mesh handedness tests.

2021-02-01 19:07 UTC, pierrebai-adsk commented
OK, I'll look at the test.

2021-02-01 19:39 UTC, pierrebai-adsk commented on test/lib/usd/translators/UsdImportMeshTest/Mesh.usda
> -        float3[] extent = [(-0.5, -0.5, -0.5), (0.5, 0.5, 0.5)]
I changed coordinates so that the meshes and subdiv don't overload, so it can more easily be manually viewed in Maya or others.

2021-02-01 19:55 UTC, JGamache-autodesk approved these changes

2021-02-01 21:59 UTC, JGamache-autodesk approved these changes

2021-02-02 23:29 UTC, HamedSabri-adsk approved these changes
Looking good. I like the consistence behavior of 'opposite' in relation to normals directions.

2021-02-04 01:45 UTC, merged