Cleanup + simplify some of the selection logic in the AL plugin
Autodesk/maya-usd pull request #1168
Opened 2021-02-10 22:30 UTC by pmolodo

I noticed that some bits of the AL selection code can be simplified / removed, some of which led to cascades of other bits being removed. In particular:

- I removed the custom code for getting nearest hit to camera, and instead rely on built-in resolveNearestToCamera
- Removed the need for `*SelectionHelper` + our own "hit tracking", as it's no longer used used the instanceIndex info, just the world space position
- Removed the need for custom `HitInfo` struct, as we never

2021-02-11 05:39 UTC, fabal approved these changes
Thanks for this @pmolodo :+1:

2021-02-12 10:08 UTC, kxl-adsk commented
@pmolodo Please check the PF log files. Looks like your change doesn't compile with USD 21.02 (and newer).

2021-02-12 10:26 UTC, kxl-adsk requested changes
Just updating the pr status to reflect that more work is needed to fix compilation with supported version of USD:
```
    /home/S/jenkins/workspace/ecg-mayausd-branch-preflight-python3-linux/ecg-maya-usd/maya-usd/plugin/al/lib/AL_USDMaya/AL/usdmaya/nodes/ProxyShapeUI.cpp:342:58: error: ‘HdxPickTokens’ was not declared in this scope
         TfToken resolveMode = selectInfo.singleSelection() ? HdxPickTokens->resolveNearestToCamera
```

2021-02-19 11:47 UTC, kxl-adsk approved these changes

2021-02-19 18:16 UTC, merged