MAYA-107276 - As a user, on the stage AE template I'd like to use Pri…
Autodesk/maya-usd pull request #1189
Opened 2021-02-17 19:15 UTC by spinell-adsk

…m Path

-Add Prim Path field in attribute editor
-Use the prime path to render with VP2RenderDelegate
-Change prim path tooltip

2021-02-18 14:39 UTC, seando-adsk commented on plugin/adsk/scripts/AEmayaUsdProxyShapeTemplate.mel
> +        //editorTemplate -suppress "primPath";
Let's just remove this line.

2021-02-18 14:39 UTC, seando-adsk approved these changes

2021-02-18 15:07 UTC, spinell-adsk commented
Please do not merge yet. I found 2 issues that I need to fix.
The first one is the primPath feature does not work as expected when the stage is create in memory.
The second one is when using primPath, the transform matrix use for rendering is wrong.

2021-02-22 18:52 UTC, spinell-adsk reviewed
@mattyjams I moved the dependency between  primPathAttr and inStageDataCachedAttr from ProxyShapeBase to ProxyShape
because we are currently have issue when the primPath changed. When we are re-computing the stage cache, if the stage is not found in a file (stage created in memory) we are creating a new in memory stage which override the current one.

Do you have any concern about this change ?

2021-02-24 09:54 UTC, kxl-adsk commented on lib/mayaUsd/nodes/proxyShapeBase.cpp
> -    retValue = attributeAffects(primPathAttr, inStageDataCachedAttr);
It's worth mentioning why this dependency doesn't belong to the base class - when computing inStageDataCachedAttr, there is nothing that reads primPathAttr unless we are calling into computeSessionLayer implementation of pxr proxy shape - https://github.com/Autodesk/maya-usd/blob/dev/plugin/pxr/maya/lib/usdMaya/proxyShape.cpp#L189

There is still the unwanted effect of clearing the stage on a change to the prim path with pxr proxy shape, but assembly workflows were not working with in-memory stages.

2021-02-24 10:00 UTC, kxl-adsk requested changes
Mostly looks good to me. I think it would be worth saving on matrix multiplication when prim path is not the default.
Additionally, this is something we would like to have a regression test for and make sure we don't regress - please check https://github.com/Autodesk/maya-usd/blob/dev/test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegatePointInstanceSelection.py for an example of such a test.

2021-02-24 18:04 UTC, mattyjams commented
> @mattyjams I moved the dependency between primPathAttr and inStageDataCachedAttr from ProxyShapeBase to ProxyShape
> because we are currently have issue when the primPath changed. When we are re-computing the stage cache, if the stage is not found in a file (stage created in memory) we are creating a new in memory stage which override the current one.
> 
> Do you have any concern about this change ?

I *think* we should be fine with this change, since the dependency is still intact from the point of the `pxrUsdProxyShape`.

I'm hoping that the performance impact of computing the local transform in `_Sync()` in `pxrUsdMayaGL` will be relatively minimal, since our typical use case is to fill the `primPath` attribute with a root prim (e.g. `/Asset`) that has no transform.

2021-02-24 18:09 UTC, mattyjams approved these changes
Seems reasonable to me, though I'd agree with @kxl-adsk that the transform computation can be avoided when `usdPrim()` yields the psuedoroot or an invalid prim.

2021-02-24 18:09 UTC, mattyjams commented on lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp
> +    // transform of the prim used for rendering.
Just a few typos in here:
considare -> considers
losesing -> losing

And looks like they're repeated in the render delegate below.

2021-03-02 18:27 UTC, kxl-adsk approved these changes

2021-03-03 11:14 UTC, kxl-adsk requested changes
We have to support older versions of USD. Please see my comments below with suggestions on how to fix compilation errors for all supported versions of USD.

2021-03-03 11:14 UTC, kxl-adsk commented on lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp
> +        if (!usdProxyShape->usdPrim().GetPath().IsAbsoluteRootPath()) {
This doesn't compile with the minimum supported version of USD, i.e. 20.02.

2021-03-03 11:14 UTC, kxl-adsk commented on lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
> +    if (!_proxyShapeData->ProxyShape()->usdPrim().GetPath().IsAbsoluteRootPath()) {
This doesn't compile with the minimum supported version of USD, i.e. 20.02.

2021-03-03 11:14 UTC, kxl-adsk commented on lib/mayaUsd/render/pxrUsdMayaGL/usdProxyShapeAdapter.cpp
> +        if (!usdProxyShape->usdPrim().GetPath().IsAbsoluteRootPath()) {
```suggestion
        if (usdProxyShape->usdPrim().GetPath() != SdfPath::AbsoluteRootPath()) {
```

2021-03-03 11:14 UTC, kxl-adsk commented on lib/mayaUsd/render/vp2RenderDelegate/proxyRenderDelegate.cpp
> +    if (!_proxyShapeData->ProxyShape()->usdPrim().GetPath().IsAbsoluteRootPath()) {
```suggestion
    if (_proxyShapeData->ProxyShape()->usdPrim().GetPath() != SdfPath::AbsoluteRootPath()) {
```

2021-03-03 22:56 UTC, kxl-adsk approved these changes

2021-03-12 10:25 UTC, merged