Updating build.md with Maya 2022
Autodesk/maya-usd pull request #1311
Opened 2021-04-06 17:59 UTC by seando-adsk

Updating build.md with Maya 2022 and dropping Maya 2018.

2021-04-06 18:03 UTC, seando-adsk commented on doc/build.md
> +|          Qt           | Maya 2019 = 5.6.1<br>Maya 2020 = 5.12.5<br>Maya 2022 = 5.15.2 | Maya 2019 = 5.6.1<br>Maya 2020 = 5.12.5<br>Maya 2022 = 5.15.2 | Maya 2019 = 5.6.1<br>Maya 2020 = 5.12.5<br>Ma
Added Maya 2022 with Qt version.

2021-04-06 18:03 UTC, seando-adsk commented on doc/build.md
> +The Universal Front End (UFE) is a DCC-agnostic component that allows Maya to browse and edit data in multiple data models. This allows Maya to edit pipeline data such as USD. UFE comes installed as
Updated to mention UFE v2 for Maya 2022.

2021-04-06 18:03 UTC, seando-adsk commented on doc/build.md
> -***NOTE:*** ```--build-args``` needs to be passed at the very end of command, after build/install location.
This is no longer required - right?

2021-04-06 18:03 UTC, seando-adsk commented on doc/build.md
> +|    Operating System   |         Windows 10        | High Sierra (10.13)<br>Mojave (10.14)<br>Catalina (10.15)    |       CentOS 7              |
Here I just reordered the versions to match how the rest of the table lists things.

2021-04-06 18:03 UTC, seando-adsk commented on doc/build.md
> +|   Compiler Requirement| Maya 2019 (VS 2017)<br>Maya 2020 (VS 2017)<br>Maya 2022 (VS 2017) | Maya 2019 (Xcode 7.3.1)<br>Maya 2020 (Xcode 10.2.1)<br>Maya 2022 (Xcode 10.2.1) | Maya 2019 (gcc 6.3.1)<b
Removed Maya 2018 (here and in all locations in file) and added Maya 2022. As per Krystian, changed the VS version to 2017 (from 2015) for Maya 2019 as we no longer support VS 2015. For Linux I mentioned both gcc 6 & 9.

2021-04-06 18:03 UTC, seando-adsk commented on doc/build.md
> +| CMake Version (min/max) |        3.13 - 3.17      |                              3.13 - 3.17                     |           3.13 - 3.17       |
Added min/max cmake versions to match our top-level CMakeLists.txt

2021-04-06 19:03 UTC, HamedSabri-adsk requested changes
- Under "Windows 10 / Command processor", still says "Visual Studio X64 2015". This should be removed since we no longer support VS 2015

- "macOS Big Sur" is missing from the list

- "Centos 8" is missing from the list

2021-04-07 19:45 UTC, HamedSabri-adsk approved these changes

2021-04-07 23:39 UTC, merged