MAYA-110368 send ufe notifications on undo and redo
Autodesk/maya-usd pull request #1412
Opened 2021-05-12 14:18 UTC by williamkrick

2021-05-12 14:32 UTC, ppt-adsk requested changes

2021-05-12 14:32 UTC, ppt-adsk commented on test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateInteractiveWorkflows.py
> +        # cmds.upAxis(axis='z')
Commented out?

2021-05-12 14:32 UTC, ppt-adsk commented on test/lib/mayaUsd/render/vp2RenderDelegate/CMakeLists.txt
> +	testVP2RenderDelegateInteractiveWorkflows.py #probably ufe v2 only
The Attributes interface is UFE v2, so this needs to be moved.

2021-05-12 14:58 UTC, ppt-adsk approved these changes

2021-05-14 20:00 UTC, williamkrick commented on lib/mayaUsd/ufe/StagesSubject.cpp
>              // We need to send some notifs so Maya can update (such as on undo
Just above here, I could modify the loop over GetResyncedPaths to get access to the SdfChangeList::entry objects and access the same flags I get in the changedInfoOnlyPaths loop.

2021-05-14 20:08 UTC, williamkrick commented on lib/mayaUsd/ufe/StagesSubject.cpp
> +                if (entry->flags.didAddInertPrim || entry->flags.didRemoveInertPrim)
This is the new filtering that catches the over primSpec creation & deletion. There are loads of other flags which could be relevant to check here.

2021-05-17 15:32 UTC, ppt-adsk approved these changes
Great work William, thanks for getting to the bottom of this!

2021-05-17 15:35 UTC, seando-adsk commented on lib/mayaUsd/ufe/StagesSubject.cpp
> +            auto ufePath = stagePath(sender) + Ufe::PathSegment(usdPrimPathStr, g_USDRtid, '/');
I have a feeling this will not pass the clang-format. Did you run it locally?

2021-05-17 15:41 UTC, seando-adsk approved these changes
Great work. Thanks for adding the comments to the existing attribute test.

2021-05-17 17:02 UTC, ppt-adsk approved these changes

2021-05-17 17:24 UTC, seando-adsk approved these changes

2021-05-19 12:46 UTC, merged