MAYA-110682 - On drag and drop of a layer with an editTarget, the edi…
Autodesk/maya-usd pull request #1444
Opened 2021-05-28 19:27 UTC by spinell-adsk

…tTarget moves to the root layer

Add a new flag (moveSubPath) to the mayaUsdLayerEditor command

When drag and drop a layer, we are currently doing 2 steps.
We are first removing the layer from it's current parent and after we are adding the layer to it's new parent.
If the layer we are moving is the edit target, the layer become not the edit target anymore because the command
for removing a layer will reset the edit target.

So to fix this issue I added a new flag to the  mayaUsdLayerEditor command to move layer into another layer.
I feel this solution it's better instead of doing tricky stuff to keep the edit target unmodified.

2021-06-01 00:14 UTC, ppt-adsk approved these changes
Looks good to me!  I agree with your assessment that a dedicated move is better than delete + add.  Thanks for the test.

2021-06-09 16:07 UTC, seando-adsk requested changes

2021-06-09 16:07 UTC, seando-adsk commented on lib/mayaUsd/commands/layerEditorCommand.cpp
> +    unsigned int _newIndex;
Why not make these private and change the constructor to take them as input?

2021-06-09 16:07 UTC, seando-adsk commented on lib/mayaUsd/commands/layerEditorCommand.cpp
> +            cmd->_newIndex = index;
Can we move line 741 here and send these as input to constructor?

2021-06-15 20:57 UTC, seando-adsk approved these changes

2021-06-15 23:48 UTC, merged