MAYA-107463 Use view-space normals and positions in UsdPreviewSurface to match
Autodesk/maya-usd pull request #1525
Opened 2021-06-28 16:48 UTC by williamkrick

the new behavior in USD.

2021-06-28 16:51 UTC, williamkrick commented on lib/mayaUsd/render/vp2ShaderFragments/shaderFragments.cpp
> +                                              _tokens->UsdUVTexture,
I guess this was the merge conflict, I will fix is properly.

2021-06-28 18:11 UTC, JGamache-autodesk requested changes

2021-06-28 18:11 UTC, JGamache-autodesk commented on lib/mayaUsd/render/vp2ShaderFragments/NwToNv.xml
> +    return (ViewIT * (vec4(Nw, 0.0))).xyz;
For HLSL I would expect something that looks like:
```
return = mul(float4(Nw, 0.0), ViewIT).xyz;
```

2021-06-28 18:11 UTC, JGamache-autodesk commented on lib/mayaUsd/render/vp2ShaderFragments/NwToNv.xml
> +    return (ViewIT * (vec4(Nw, 0.0))).xyz;
And Cg is most probably:
```
return mul(ViewIT, float4(Nw, 0.0f)).xyz;
```

2021-06-28 18:11 UTC, JGamache-autodesk commented on lib/mayaUsd/render/vp2ShaderFragments/usdPreviewSurfaceLightingAPI2.xml
> +
Debugging output?

2021-07-05 16:05 UTC, JGamache-autodesk approved these changes

2021-07-08 18:10 UTC, closed without merging