Add tests for sets command and for isolate select in Vp2RenderDelegate.
Autodesk/maya-usd pull request #1678
Opened 2021-09-02 18:34 UTC by williamkrick

2021-09-02 18:36 UTC, williamkrick commented
I have one additional Maya change that is necessary to prevent the isolate select test from crashing, so do not merge this until that change is available.

2021-09-03 14:53 UTC, ppt-adsk requested changes
testSetsCmd looks pretty good already, does need some undo / redo testing though.

2021-09-03 14:53 UTC, ppt-adsk commented on test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateIsolateSelect.py
> +        # cmds.upAxis(axis='z')
Commented out?

2021-09-03 14:53 UTC, ppt-adsk commented on test/lib/ufe/testSetsCmd.py
> +import mayaUsd.ufe
Don't think any of these are used.

2021-09-03 14:53 UTC, ppt-adsk commented on test/lib/ufe/testSetsCmd.py
> +import os
Unused.

2021-09-13 14:06 UTC, ppt-adsk requested changes

2021-09-13 14:06 UTC, ppt-adsk commented on test/lib/ufe/testSetsCmd.py
> +        # Undo, Redo
Looks like redo() never actually made it into the file :)

2021-09-20 14:07 UTC, ppt-adsk approved these changes

2021-09-21 14:37 UTC, JGamache-autodesk approved these changes

2021-09-21 14:37 UTC, JGamache-autodesk commented on test/lib/mayaUsd/render/vp2RenderDelegate/testVP2RenderDelegateIsolateSelect.py
> +        cmds.isolateSelect("modelPanel4", state=1)
Can this function use the result of `mayaUtils.activeModelPanel()` as first parameter? Would it make the test more robust?

2021-09-22 14:09 UTC, merged