[base] fix for proxyShapes in vp2 to display shaders bound to "glslfx:surface" material output
Autodesk/maya-usd pull request #1870
Opened 2021-12-01 18:01 UTC by nxkb

Small change to make sure materials connected to "glslfx:surface" will show up as well as the unqualified "surface" port in viewport 2.0.

This fix makes sure the glslfx ports are also displayed when maya_usd is not built with "materialX" support.

(This matches the Storm implementation used by Usdview)

2021-12-01 19:42 UTC, JGamache-autodesk requested changes

2021-12-01 19:42 UTC, JGamache-autodesk commented on lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
> +}
This new API was introduced in USD 21.05. Can you put the deprecated code under a 
```
#if PXR_VERSION < 2105
    /// Deprecated code
#else
    /// Code for new API
#endif
```
So it builds and runs on all supported USD versions, yet has visibility so we can remove it a year from now?

2021-12-02 23:30 UTC, nxkb commented on lib/mayaUsd/render/vp2RenderDelegate/render_delegate.cpp
> +}
sounds good. This is done, all the various cases should be covered.

2021-12-03 17:55 UTC, JGamache-autodesk approved these changes

2021-12-06 14:35 UTC, JGamache-autodesk approved these changes

2021-12-06 14:54 UTC, merged