MAYA123876 adding docs about saving layers
Autodesk/maya-usd pull request #2483
Opened 2022-07-13 20:34 UTC by pierrebai-adsk

2022-07-15 19:27 UTC, ppt-adsk requested changes
Massive amount of work, thanks for doing this!  In general, I would remove internal details, and re-work historical descriptions and turn them into descriptions of the current state of the code.

2022-07-15 19:27 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +
Remove, keep only in internal Wiki.

2022-07-15 19:27 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +found in the Stage caches.
Remove the last sentence, document the new code.

2022-07-15 19:27 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +The Layer Manager also does this for the session layer. Except there was
Also does what?

2022-07-15 19:27 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +external USD files.
Remove most of this, describe the new code.

2022-07-15 19:27 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +
Remove, keep only on in internal Wiki.

2022-07-15 19:27 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +that would lose the session.
Remove historical reference.

2022-07-15 19:27 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +(The layers are attributes on the layer manager node.)
Remove historical references, document state of current code.

2022-07-18 15:09 UTC, ppt-adsk requested changes
Almost there, only very minor typos and details!

2022-07-18 15:09 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +## Save Architecture Challenge
Would word it as "Challenges" plural, for consistency with the text below.

2022-07-18 15:09 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +### Where are stage caches created is Maya USD?
"is Maya USD" --> "in Maya USD".

2022-07-18 15:09 UTC, ppt-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +because we don't have it and we want ot find a stage with the root layer and
"ot" --> "to"

2022-07-18 16:05 UTC, pierrebai-adsk commented on lib/mayaUsd/nodes/Layer_Saving_Docs.md
> +This layer-saving process is not customizable. The USD plugin can provide
not was left behind, removed.

2022-07-18 17:43 UTC, ppt-adsk approved these changes
Great work, thanks for doing this!

2022-07-18 17:48 UTC, ppt-adsk commented
No pre-flight required, documentation only.

2022-07-18 21:24 UTC, merged