Add menu item to graph a material
Autodesk/maya-usd pull request #2532
Opened 2022-08-05 09:32 UTC by stefanminning-autodesk

2022-08-05 13:16 UTC, JGamache-autodesk requested changes

2022-08-08 20:59 UTC, ppt-adsk commented on lib/mayaUsd/ufe/UsdContextOps.cpp
> +#if UFE_PREVIEW_VERSION_NUM >= 4010
Hey, hope I have this right, but I'm pretty sure you can do this already, with a Decorator pattern:
https://en.wikipedia.org/wiki/Decorator_pattern
I don't think studios would want to do it this way --- typically they're interested in a simple Python callback scheme, so what I'm explaining below might not be for third parties, but I think it's fine for us.

Essentially you want to do the following (similar to what we're doing for the Hierarchy and Transform3d handlers):

1. In the initialization of your plugin, ask the UFE run-time manager what the current USD context ops handler is: `auto currentUsdOpsHandler = RunTimeMgr::getInstance().contextOpsHandler(theUsdRtId);`
2. Create your own wrapper context ops handler, which will receive the USD context ops handler from (1) as a constructor argument: `auto myUsdOpsHandler = MyContextOpsHandler::create(currentUsdOpsHandler);`.
3. Set this new wrapper context ops handler as the current USD context ops handler, using the UFE run-time manager: `RunTimeMgr::getInstance().setContextOpsHandler(theUsdRtId, myUsdOpsHandler);`.
Don't forget to undo this in your plugin finalization.  Your wrapper context ops handler will look like this:
```
MyContextOpsHandler::MyContextOpsHandler(const ContextOpsHandler::Ptr& nextHandler) : _nextHandler(nextHandler)
{}

ContextOps::Ptr contextOps(const SceneItem::Ptr& item) const override {
    // Get the context ops interface from the next handler.
    auto wrappedOps = _nextHandler->contextOps(item);
    // Wrap it up inside our decorator context ops.
    return MyContextOps::create(wrappedOps);
}
```
Your decorator context ops will look like this:
```
MyContextOps::MyContextOps(const ContextOps::Ptr& wrappedOps) : _wrappedOps(wrappedOps)
{}

SceneItem::Ptr MyContextOps::sceneItem() const override { return _wrappedOps->sceneItem(); }

Items MyContextOps::getItems(const ItemPath& itemPath) const override {
    // Call the wrapped ops first, get its context op items.
    auto items = _wrappedOps->getItems(itemPath);
    // If the item path is relevant for us, append our item(s)
    if (thisOneIsRelevantForUs(itemPath)) {
        items.appendWhateverIsNeeded();
    }
    return items;
}

// Not sure if default implementation of doOp() is sufficient, it just calls doOpCmd().

UndoableCommand::Ptr MyContextOps::doOpCmd(const ItemPath& itemPath) override {
    // If item path is for us, handle it.
    if (thisOneIsRelevantForUsToDo(itemPath)) {
        return ourDoOpCmd(itemPath);
    }
    else {
        return _wrappedOps->doOpCmd(itemPath);
    }
}
```
Hope this hand-wavy explanation is actually helpful, let me know if I'm way off the mark.

2022-08-09 08:02 UTC, stefanminning-autodesk commented on lib/mayaUsd/ufe/UsdContextOps.cpp
> +#if UFE_PREVIEW_VERSION_NUM >= 4010
Thanks for the detailed explanation, @ppt-adsk. I will give it a try.

2022-08-10 11:25 UTC, stefanminning-autodesk commented
Thanks again, @ppt-adsk: With your example, I managed to implement the required functionality entirely in our plugin with no changes to MayaUSD. 

Closing this PR as it's obsolete.

2022-08-10 11:25 UTC, closed without merging