MAYA-124365 test prim undo delete vs display layer
Autodesk/maya-usd pull request #2625
Opened 2022-09-26 13:30 UTC by pierrebai-adsk

2022-09-26 13:31 UTC, pierrebai-adsk commented on test/lib/ufe/testDisplayLayer.py
> +        cmds.undoInfo(openChunk=1)
When issuing commands in scripts, we need to create undo check by hand if we want them... display layer restoration only work when we have a undo chunk.

2022-10-03 15:12 UTC, ppt-adsk requested changes

2022-10-03 15:12 UTC, ppt-adsk commented on test/lib/ufe/testDisplayLayer.py
> +        cmds.undo()
This feels very awkward.  I know you've mentioned that in the interactive application all commands are chunked, so to test what the interactive application is doing I would follow your suggestion and open an explicit undo chunk before line 338.

2022-10-03 15:13 UTC, ppt-adsk commented on test/lib/ufe/testDisplayLayer.py
> +    @unittest.skipUnless(mayaUtils.ufeSupportFixLevel() >= 6, "Requires Display Layer Ufe item delete undo fix.")
Is the fix level still O.K.?

2022-10-03 16:04 UTC, pierrebai-adsk commented on test/lib/ufe/testDisplayLayer.py
> +    @unittest.skipUnless(mayaUtils.ufeSupportFixLevel() >= 6, "Requires Display Layer Ufe item delete undo fix.")
Yes, it is still 6 for that fix.

2022-10-03 17:39 UTC, pierrebai-adsk commented
Another PF where the interactive Linux builds failed to start. The interactive Linux instances must be down. Unrelated to my changes, all other builds passed.

2022-10-03 18:03 UTC, ppt-adsk approved these changes

2022-10-06 20:14 UTC, merged