LOOKDEVX-784 | Makes use of USD_FORCE_DEFAULT_MATERIALS_SCOPE_NAME an…
Autodesk/maya-usd pull request #2658
Opened 2022-10-17 20:20 UTC by feldstj

…d MAYAUSD_MATERIALS_SCOPE_NAME environment variables for generating the scope name for assigned materials.

2022-10-24 15:28 UTC, seando-adsk requested changes

2022-10-24 15:28 UTC, seando-adsk commented on lib/mayaUsd/ufe/UsdUndoMaterialCommands.cpp
> +        }
Why not use "TfGetenv" which returns you a std::string and you can provide a default value if the env var is not set.

2022-10-27 20:38 UTC, JGamache-autodesk approved these changes

2022-10-28 12:42 UTC, neilh-adsk reviewed
Un related, but is the Environment variable documented ?

2022-10-28 13:19 UTC, feldstj commented
> Un related, but is the Environment variable documented ?

I'm assuming we'll have documentation somewhere for at least the MAYAUSD variable.

2022-10-28 13:29 UTC, neilh-adsk approved these changes

2022-10-28 13:34 UTC, merged