Fix lost connection for output port with parent
Autodesk/maya-usd pull request #2729
Opened 2022-11-17 08:14 UTC by alicedegirolamo

Simple fix.
When renaming output ports on the compound, connections with the parent are lost. 
This was caused by the fact that the update of connections with the new path was done on the children of the parent and not also on the parent itself.

2022-11-17 14:10 UTC, JGamache-autodesk submitted a review, later dismissed
Very good. Can you add a unit test that checks this bug stays fixed?

2022-11-18 12:44 UTC, alicedegirolamo commented
> Very good. Can you add a unit test that checks this bug stays fixed?

Sure! I'm going to do that.

2022-11-24 08:30 UTC, alicedegirolamo commented
> Very good. Can you add a unit test that checks this bug stays fixed?

Ok, I pushed and tested the new test. I had to add a new simple compound to the .usd since I didn't find in the sample folder a compound suitable for my test case.

2022-11-24 15:59 UTC, JGamache-autodesk commented
Preflight was successful (after a review of the logs). The two failure to upload artifacts happened after the tests succeeded.

2022-11-24 16:00 UTC, JGamache-autodesk approved these changes

2022-11-24 19:35 UTC, hodoulp requested changes

2022-11-24 19:35 UTC, hodoulp commented on lib/mayaUsd/ufe/UsdAttributes.cpp
> +static void setConnectionsWithChildren(
I find the name ambiguous. It could be:
- `setConnectionsOfAllChildren()`
- `updateChildrenConnections()` +1

2022-11-24 19:35 UTC, hodoulp commented on lib/mayaUsd/ufe/UsdAttributes.cpp
> +    for (auto& attribute : prim.GetAttributes()) {
It could/should be a const variable like `const auto& attribute`.

2022-11-24 19:35 UTC, hodoulp commented on lib/mayaUsd/ufe/UsdAttributes.cpp
> +    const SdfPath&         oldPropertyPath,
The method does not set the connection it only updates existing connections:
`updateConnections()`

2022-11-24 19:35 UTC, hodoulp commented on lib/mayaUsd/ufe/UsdAttributes.cpp
> +    }
[Question] Should that method be recursive to process children of children, etc. ?

2022-11-24 19:35 UTC, hodoulp commented on test/lib/ufe/testAttributes.py
> +        cmd = compoundAttrs.renameAttributeCmd("outputs:out","outputs:out1")
typo `"outputs:out","outputs:out1"` -> `"outputs:out", "outputs:out1"`

2022-11-24 19:35 UTC, hodoulp commented on test/lib/ufe/testAttributes.py
> +        self.assertEqual(dstAttr.name, 'outputs:out')
Could enhance the test with `cmds.undo()` ?

2022-11-28 14:56 UTC, JGamache-autodesk approved these changes

2022-11-28 20:25 UTC, hodoulp commented
I think that there are two main pending points:
- The recursivity question [here](https://github.com/Autodesk/maya-usd/pull/2729/files/218a234bccfb647f2ea3b5bf7e1b05ff75846762#diff-db3eb61f02eef0d4aa689c03f427b680616a013e850e3ea7870664d3e009a191R527)
- the undo() / redo() improvement in the unit test

But I will @JGamache-autodesk and Orn have the last call on that.

2022-11-28 20:25 UTC, hodoulp approved these changes

2022-11-28 21:46 UTC, JGamache-autodesk commented
- Going recursive is unnecessary on well constructed graphs. Connections on outer ports can only come from nodes in the englobing compound (or inner ports of the englobing compound). Connections on inner ports can only come from nodes directly inside the compound.
- Agreed that testing undo redo would be nice.

2022-11-29 12:42 UTC, alicedegirolamo commented
> I think that there are two main pending points:
> 
>     * The recursivity question [here](https://github.com/Autodesk/maya-usd/pull/2729/files/218a234bccfb647f2ea3b5bf7e1b05ff75846762#diff-db3eb61f02eef0d4aa689c03f427b680616a013e850e3ea7870664d3e009a191R527)
> 
>     * the undo() / redo() improvement in the unit test
> 
> 
> But I will @JGamache-autodesk and Orn have the last call on that.

Yes, I have to add the undo/redo test but I'm having problems compiling the updated Maya. As soon as I fixed my build I'm going to add it. Sorry for the wait.

2022-11-30 13:36 UTC, JGamache-autodesk approved these changes

2022-11-30 13:53 UTC, hodoulp approved these changes

2022-12-01 20:47 UTC, neilh-adsk approved these changes

2022-12-01 20:47 UTC, merged