Shorten nice names by trimming schema name
Autodesk/maya-usd pull request #2818
Opened 2023-01-12 15:59 UTC by JGamache-autodesk

Some attribute names use namespaces that are copies of the schema name. When displaying UI names we want to strip that redundant information.

2023-01-12 16:00 UTC, JGamache-autodesk commented
Before and after for an exported spotlight:
![UiNameSpotLight](https://user-images.githubusercontent.com/56274617/212116777-5b57d9a9-97aa-4ca9-951b-f1277d0d3331.PNG)

2023-01-12 16:46 UTC, feldstj requested changes

2023-01-12 16:46 UTC, feldstj commented on lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
> +        # includes the instance in the title. This allows up to optimally trim
allows up -> allows us

2023-01-12 16:46 UTC, feldstj commented on lib/mayaUsd/ufe/UsdAttributeHolder.cpp
> +                    // If the parameter name does not start with the templte, it does not belong to
templte -> template

2023-01-12 16:47 UTC, feldstj commented
Pretty cool change. Just a few minor spelling issues.

2023-01-12 18:24 UTC, feldstj approved these changes

2023-01-12 19:08 UTC, JGamache-autodesk commented
@seando-adsk Ready for merge.

2023-01-13 15:42 UTC, seando-adsk approved these changes

2023-01-13 16:23 UTC, merged