MAYA-126541 - Create a more extensive unit test for display layer support during USD to USD duplication
Autodesk/maya-usd pull request #2866
Opened 2023-02-06 18:13 UTC by vlasovi

2023-02-14 21:12 UTC, seando-adsk requested changes
Could you please add a unit test as requested by PierreB in the PR #2747

2023-02-15 13:22 UTC, vlasovi commented
@seando-adsk The test that I added verfies the fix introduced in the PR https://github.com/Autodesk/maya-usd/pull/2747 , which is "duplicating from USD to USD a node that is not in the stage root", and I think that's what @pierrebai-adsk wanted me to verify. I'm not sure what else I need to do here.

2023-02-15 21:13 UTC, seando-adsk reviewed
Ah sorry about that. I missed that from the new test. Maybe add a comment stating that. If you do, don't worry about re-running the preflight.

2023-02-16 18:36 UTC, seando-adsk approved these changes

2023-02-16 18:36 UTC, merged