MAYA-127700 - Extend Viewport and Outliner menus to allowing assigning new or existing materials
Autodesk/maya-usd pull request #2896
Opened 2023-02-23 13:34 UTC by stefanminning-autodesk

# Description
This PR extends the Outliner and Viewport menus with new entries that allow the user to assign new or existing materials to objects. 
The difficulty here is the jumping between the different languages: Going from MEL via Python into C++ doesn't strike me as the most elegant approach, but I wasn't sure how else to handle it, since the viewport menu itself lives in MEL.

Simple unit tests are included for the newly added Commands.

# TODOs
Currently, the renderers and their materials (MaterialX, USD, Arnold) are hard-coded; this was largely ported from existing code in `UsdContextOps.cpp`. A future iteration should feature a more robust solution that queries the loaded renderers (including third-party!) for their supported materials.

2023-02-23 14:21 UTC, seando-adsk commented
@stefanminning-autodesk pr-build doesn't work for github. To run a preflight here set the assignee to ecp-maya-devops-adsk

2023-02-23 17:20 UTC, JGamache-autodesk requested changes

2023-02-23 17:20 UTC, JGamache-autodesk commented on plugin/adsk/plugin/adskMaterialCommands.cpp
> +    // TODO: Replace hard-coded materials with dynamically generated list.
No need for a TODO here. There will always be only one preview material.

2023-02-23 17:20 UTC, JGamache-autodesk commented on plugin/adsk/plugin/adskMaterialCommands.cpp
> +            if (prim.GetTypeName() == materialType) {
I would prefer you use the stronger `if (UsdShadeMaterial(prim))` as filter.

2023-02-23 17:20 UTC, JGamache-autodesk commented on plugin/adsk/plugin/adskMaterialCommands.h
> +struct MxShaderMenuEntry
I don't think this struct is used. Can you recheck and see it it can be removed?

2023-02-23 17:20 UTC, JGamache-autodesk commented on plugin/adsk/scripts/USDMenuProc.mel
> +                                cmd = contextOps.doOpCmd(['Assign New Material', 'USD', '" + $material + "']);\
The `'USD'` part could be misleading. Looks like the context ops are only interested in items 0 and 2 in that list. Maybe you should leave that middle string blank?

2023-02-23 17:20 UTC, JGamache-autodesk commented on test/lib/mayaUsd/utils/testMaterialCommands.py
> +
You could add a test for `ContextOp::getItems()` to check if the subtrees of add new/existing material are correctly populated.

2023-02-23 19:42 UTC, seando-adsk requested changes

2023-02-23 19:42 UTC, seando-adsk commented on plugin/adsk/plugin/adskMaterialCommands.cpp
> +    syntax.addFlag("-si", "-sceneItem", MSyntax::kString);
I don't think you need or should use a flag like this. Its not really a "sceneitem". It is actually a string which is interpreted as a Ufe PathString. 

Instead look at calling ```addArg(MSyntax::kString)``` then simply get that string arg. There are examples of this in our code already. Plus you should probably set the ```syntax.enableQuery/enableEdit``` as well.

2023-02-28 14:08 UTC, JGamache-autodesk commented on lib/mayaUsd/ufe/UsdContextOps.cpp
> +            MString script;
Yes.

2023-03-07 14:15 UTC, JGamache-autodesk approved these changes

2023-03-07 14:15 UTC, JGamache-autodesk commented on lib/mayaUsd/ufe/UsdContextOps.cpp
> +                MStatus      status = material.split('/', pathAndMaterial);
Why not a reverse find for the last "/" that will allow you to split the string in two at the right location?

2023-03-07 14:15 UTC, JGamache-autodesk commented on lib/mayaUsd/ufe/UsdContextOps.cpp
> +                // Expects a string in the format "/path1/path2|Material".
Is that comment correct? I don't see any splitting on the "|" in the below code.

2023-03-07 16:32 UTC, JGamache-autodesk requested changes

2023-03-07 16:32 UTC, JGamache-autodesk commented on plugin/adsk/scripts/USDMenuProc.mel
> +                                cmd.execute();")`;
This is where you need to use `Ufe::UndoableCommandMgr::instance().executeCmd(cmd);`

2023-03-08 13:25 UTC, seando-adsk commented
@stefanminning-autodesk According to our [coding guidelines](https://github.com/Autodesk/maya-usd/blob/dev/doc/codingGuidelines.md) you need to use clang-format v10.0.0

2023-03-08 14:31 UTC, JGamache-autodesk commented on test/lib/mayaUsd/utils/testMaterialCommands.py
> +                             'MaterialX/glTF PBR|ND_gltf_pbr_surfaceshader',
Earlier versions of MaterialX in earlier versions of USD do not have this `glTf` shader. Removing this line should help the unit test succeed on legacy configurations.

2023-03-08 14:36 UTC, JGamache-autodesk commented on plugin/adsk/plugin/CMakeLists.txt
> +        adskMaterialCommands.cpp
You need to add this to the list TARGET_NAME only is UFE_FOUND is true. This will fix the `ecg-mayausd-branch-preflight-2019-no-ufe-windows` build.

2023-03-08 14:40 UTC, JGamache-autodesk approved these changes

2023-03-08 16:03 UTC, JGamache-autodesk commented on test/lib/mayaUsd/utils/testMaterialCommands.py
> +        print(expectedMaterials)
Might need something like:
```
    if(CMAKE_WANT_MATERIALX_BUILD)
        list(APPEND TEST_SCRIPT_FILES
            testMaterialCommands.py
        )
    endif()
```
In the CMakeLists.txt.

2023-03-08 19:01 UTC, seando-adsk approved these changes
Looks good now. Thanks.

2023-03-08 19:33 UTC, JGamache-autodesk submitted a review, later dismissed

2023-03-09 16:06 UTC, JGamache-autodesk approved these changes

2023-03-10 21:07 UTC, seando-adsk approved these changes

2023-03-10 21:08 UTC, merged