Update the title of Duplicate As Usd Data Option Dialog to match. Also refactored various files that used duplicate as Maya data while the business logic within them meant to perform duplicate as Usd data.
Autodesk/maya-usd pull request #2916
Opened 2023-03-02 17:58 UTC by AramAzhari-adsk

Update the title of Duplicate As Usd Data Option Dialog to match. Also refactored various files that used duplicate as Maya data while the business logic within them meant to perform duplicate as Usd data.

2023-03-02 18:52 UTC, pierrebai-adsk commented on lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
> +    register('kDuplicateAsUsdDataOptionsTitle', 'Duplicate As Usd Data Options')
USD should be all in uppercase.

2023-03-02 18:53 UTC, pierrebai-adsk requested changes
Only need to fix the captions to use USD

2023-03-02 18:56 UTC, AramAzhari-adsk commented on lib/mayaUsd/resources/scripts/mayaUsdLibRegisterStrings.py
> +    register('kDuplicateAsUsdDataOptionsTitle', 'Duplicate As Usd Data Options')
done

2023-03-02 21:15 UTC, pierrebai-adsk approved these changes

2023-03-03 13:03 UTC, vlasovi approved these changes

2023-03-03 17:02 UTC, merged