Remove explicit call to sceneIndex::Populate
Autodesk/maya-usd pull request #2983
Opened 2023-03-28 23:44 UTC by dj-mcg

In most recent USD, Populate is called from within SetStage, so there is no need to callsites to call it explicitly

2023-03-30 16:30 UTC, perrauo-adsk requested changes
Why the header inclusion?

2023-03-30 16:58 UTC, dj-mcg commented
> Why the header inclusion? Seems unrelated no?

Because I couldn't build without it. See:
https://github.com/Autodesk/maya-usd/pull/2975

2023-03-30 17:00 UTC, perrauo-adsk approved these changes

2023-03-30 17:41 UTC, merged

2023-04-03 23:11 UTC, perrauo-adsk commented
@dj-mcg Could you point out to the Pixar change that fixes this. This removal is now causing issues on my end.

2023-04-07 17:51 UTC, dj-mcg commented
My apologies! I had assumed that change would land with 2305 - thanks for the fix