MAYA-129155 fix shiboken crash
Autodesk/maya-usd pull request #3057
Opened 2023-05-03 17:44 UTC by pierrebai-adsk

The crash was due to the cleanup done by Maya with Shiboken. I believe the problem is that by the time the cleanup is called, the USD plugin is already unloaded or already destroyed in Qt UI.

- Don't use Shiboken to convert a layout raw pointer into a QWidget.
- Instead, provide a function to retrieve the window name that contains a layout.
- Then find the window by name.

2023-05-03 20:48 UTC, seando-adsk requested changes

2023-05-03 20:48 UTC, seando-adsk commented on lib/mayaUsd/python/CMakeLists.txt
> +        Qt5::Widgets
Sorry I don't like this. We should not make this lib link with Qt. The only lib in our repo that should link with Qt is the mayaUsdUI lib.

2023-05-04 15:00 UTC, pierrebai-adsk commented
Related PF is 955.

2023-05-04 18:17 UTC, seando-adsk commented on plugin/adsk/scripts/mayaUsd_USDRootFileRelative.py
> +            print('Could not find dialog named %s' % maya_window_name)
What is the purpose of the print? The user cannot really do anything to fix this error right? If you want the user to know about it then maybe use cmds.warning().

2023-05-04 18:17 UTC, seando-adsk approved these changes

2023-05-05 18:04 UTC, seando-adsk approved these changes

2023-05-05 18:04 UTC, merged