EMSUSD-121 - Use display color when texture mode is disabled
Autodesk/maya-usd pull request #3272
Opened 2023-08-11 19:28 UTC by samuelliu-adsk

2023-08-14 13:32 UTC, vlasovi commented on lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
> +                || !(reprToken == HdReprTokens->smoothHull)) {
This looks wrong. If your intention here is to choose sFallbackShaderPrimvars for untextured mode then you need to have something like: || (reprToken == HdReprTokens->smoothHullUntextured)

2023-08-14 13:42 UTC, vlasovi commented on lib/mayaUsd/render/vp2RenderDelegate/mesh.cpp
> +                || !(reprToken == HdReprTokens->smoothHull)) {
Also, in case where hasColor is true below, we don't use fallback shader. So I guess this logic should be consistent

2023-08-21 16:03 UTC, vlasovi commented on lib/mayaUsd/render/vp2RenderDelegate/mesh.h
> +#include <mayaUsd/base/tokens.h>
I think this include can be in cpp file

2023-08-21 16:06 UTC, vlasovi requested changes
Looks very good now. One tiny thing left: please move the "tokens.h" include into cpp. In general, the less includes we have in header files, the faster the compilation.

2023-08-21 20:42 UTC, JGamache-autodesk approved these changes

2023-08-22 13:04 UTC, vlasovi approved these changes

2023-08-22 20:08 UTC, merged