Add untextued mode to user pref
Autodesk/maya-usd pull request #3361
Opened 2023-10-03 15:49 UTC by samuelliu-adsk

2023-10-04 13:28 UTC, seando-adsk requested changes
You also need to add your new pref case to:
- mayaUsd_PrefInitOptionVars() - both the 2022 (and earlier case) and else (using new -init flag).
- mayaUsd_PrefUpdate()

2023-10-04 13:28 UTC, seando-adsk commented on plugin/adsk/scripts/mayaUsd_preferenceTab.mel
> +		}
You should also add your new pref to the prefOptionVars list above.

2023-10-05 14:05 UTC, seando-adsk requested changes
You still need to add your new option var to mayaUsd_PrefUpdate()

2023-10-06 15:45 UTC, seando-adsk commented on plugin/adsk/scripts/mayaUsd_preferenceTab.mel
> +			radioButtonGrp -e -v1
radioButtonGrp doesn't have -v1 flag, you need to use -sl flag (like above) and convert the boolean option: false (0), true (1) into the select flag which 1-based.

2023-10-06 15:46 UTC, seando-adsk commented on plugin/adsk/scripts/mayaUsd_preferenceTab.mel
> +		radioButtonGrp -e -select $v usdPrefUntexturedMode;
See my comment below about boolean optionVar vs 1-based select flag.

2023-10-06 15:46 UTC, seando-adsk requested changes
Sorry I didn't catch the radioButton vs checkBox before. Some more changes are needed.

2023-10-06 23:27 UTC, samuelliu-adsk commented on plugin/adsk/scripts/mayaUsd_preferenceTab.mel
> +	ogs -reset;
I added another viewport refresh here, because if we reset to factoryDefault we need to refresh to show the change

2023-10-11 13:25 UTC, seando-adsk approved these changes

2023-10-13 14:05 UTC, merged