EMSUSD-632 prevent root metadata changes when not targeting root
Autodesk/maya-usd pull request #3398
Opened 2023-10-18 19:09 UTC by pierrebai-adsk

- Add a applyRootLayerMetadataRestriction helper function to enforce not modifying the root layer metadata when not targeting the root layer.
- The only restriction applied is about the default prim.
- Call it from within the applyCommandRestriction helper function.

2023-10-19 18:50 UTC, pierrebai-adsk commented
The Attribute Editor now uses the command and can be undone.

2023-10-19 19:23 UTC, pierrebai-adsk commented
Once again, the only PF failure is one interactive test in a single PF where a USD file was left behind in the temp folder from e previous PF, that failure can be ignored.

2023-10-20 19:32 UTC, seando-adsk requested changes
Great work. Just a couple of very minor comments.

2023-10-20 19:32 UTC, seando-adsk commented on plugin/adsk/scripts/AETemplateHelpers.py
> +        OpenMaya.MGlobal.displayError((str(e)))
Not a big deal, but isn't there an extra set of () here?

2023-10-20 19:32 UTC, seando-adsk commented on test/lib/ufe/testDefaultPrimCmds.py
> +# Copyright 2020 Autodesk
Should be current year.

2023-10-23 19:14 UTC, seando-adsk approved these changes

2023-10-25 13:47 UTC, merged