Add test cases for material fanned out file nodes
Autodesk/maya-usd pull request #3403
Opened 2023-10-20 18:40 UTC by AramAzhari-adsk

This is a follow up to https://github.com/Autodesk/maya-usd/pull/3366 to add test cases. 
There is also a minor change from MObjectArray to MObjectHandleUnorderedSet.

The test scene contains 5 cubes that cover various materials:

File Node fanning out to two other File Nodes to the same Material (Lambert):
![image](https://github.com/Autodesk/maya-usd/assets/123101715/7ac61c85-717f-49d8-9ae3-fcb3c6d54e4e)

File Node fanning out to two other File Nodes to the same Material (Standard Surface):
![image](https://github.com/Autodesk/maya-usd/assets/123101715/8e1a9dc4-81be-4ba7-bf6d-6e81dd5db32a)

File Node fanning out to two other File Nodes to the same Material (USD Preview Surface):
![image](https://github.com/Autodesk/maya-usd/assets/123101715/be10ec53-99fc-4e5d-aac8-a710b3377bab)

File Node fanning out to two other File Nodes to different Materials (Lambert):
![image](https://github.com/Autodesk/maya-usd/assets/123101715/9ca11867-97c3-419a-9f4d-ab9b22adca4e)

2023-10-20 19:24 UTC, JGamache-autodesk requested changes
This is not actually testing the fix you implemented, which was about stray file nodes.

Please add checks that:

1 - For UsdPreviewSurface exports:
    file13 and file15 are present for lambert4, file14 is not
    file16 and file18 are present for standardSurface2, file17 is not
      ....
    file10 is present for lambert3, file11 and file12 are not
    file12 is present for lambert2, file10 and file11 are not

2- For MaterialX exports:
    file13, file14 and file15 are present for lambert4
    file16, file17 and file18 are present for standardSurface2
      ....
    file10 and file11 are present for lambert3, file12 is not
    file11 and file12 are present for lambert2, file10 is not

2023-10-20 19:24 UTC, JGamache-autodesk commented on lib/mayaUsd/fileio/shading/shadingModeUseRegistry.cpp
>                  bool allowedNode = false;
Using a MObjectHandleUnorderedSet has powerful benefits:

```suggestion
                if (!allowedNodes.count(dstPlug.node()) {
                    continue
                }
```

This replaces the whole `for` loop, and all `allowedNode` boolean logic.

2023-10-20 19:24 UTC, JGamache-autodesk commented on test/lib/usd/translators/CMakeLists.txt
> +	testUsdExportFannedOutFileNodesMaterial.py
Minor: Tab vs spaces. Can you clean that up please.

2023-10-25 16:11 UTC, AramAzhari-adsk commented
Updated the test logic to correctly check for nodes that must be included and the nodes that must not be included. I also locally changed the list to make sure it is functioning properly.

Note: The purpose of the fix in https://github.com/Autodesk/maya-usd/pull/3366 was to prevent adding nodes that do not exist in Maya's dependency graph for each material. The fix or its test does **not** cover cases where an unsupported connection is not translated onto USD, which may end up containing zombie nodes that are not connected to anything. That is a separate issue and I will create a ticket to have it fixed based on priority.

2023-10-25 16:18 UTC, JGamache-autodesk submitted a review, later dismissed

2023-10-25 19:47 UTC, JGamache-autodesk approved these changes

2023-10-26 13:34 UTC, seando-adsk approved these changes

2023-10-26 13:45 UTC, merged