EMSUSD-603 - Errors when trying to cache a rig with merge transforms ON and namespaces OFF
Autodesk/maya-usd pull request #3474
Opened 2023-11-20 21:52 UTC by samuelliu-adsk

- The issue is caused by transforms merged to parent node, which will cause a mismatch between SDF and DAG paths and ultimately cause clashes. We should only write to the node's parent node when it a shape node.
- Removed the `channel1` part of the unity test because that is attribute is created because of the bug above. I compared the cache to usd result to a normal export and the files matches (there's no `channel1 ` in normal export usd files)

2023-11-20 22:08 UTC, samuelliu-adsk commented on test/lib/mayaUsd/fileio/testCacheToUsd.py
> -        self.assertIn("xformOp:rotateXYZ:channel1", value)
Removed these two lines because those are not valid any more, but I don't know if there's any other ways to test it...

2023-11-20 22:09 UTC, samuelliu-adsk commented on lib/mayaUsd/fileio/writeJobContext.cpp
>      // write to the parent (transform) path instead.
As the comment stated, we should only write to parent if the current node is a shape node

2023-11-21 16:34 UTC, pierrebai-adsk commented on lib/mayaUsd/utils/util.h
> +bool isShape(const MDagPath& dagPath);
I think we shoudl export it by adding MAYAUSD_CORE_PUBLIC, like the other functions.

2023-11-21 16:35 UTC, pierrebai-adsk requested changes
Only need that export and it will be all good

2023-11-21 22:38 UTC, pierrebai-adsk approved these changes

2023-11-22 21:54 UTC, merged