EMSUSD-871 - Locked layer status persists between Maya sessions
Autodesk/maya-usd pull request #3638
Opened 2024-02-27 15:56 UTC by AramAzhari-adsk

- If a layer has a LayerLock_Locked status, the status is saved into a proxy shape attribute named "lockedLayers" (brief name: lockla) and is stored in the maya file.
- Moved the core of locking mechanism into layerLocking .h and .cpp

2024-02-27 18:32 UTC, pierrebai-adsk commented on lib/mayaUsd/utils/layerLocking.h
> +// copyLayerLockingToAttribute(const PXR_NS::UsdStage& stage, MayaUsdProxyShapeBase& proxyShape);
Some commented-out code remained here,

2024-02-27 18:33 UTC, pierrebai-adsk requested changes
Just a few small changes, needed.

2024-02-27 22:44 UTC, AramAzhari-adsk commented on lib/mayaUsd/utils/layerLocking.cpp
> +bool isLayerLocked(const PXR_NS::SdfLayerRefPtr& layer)
Note: this is going to be used in EMSUSD-879.

2024-02-28 14:02 UTC, pierrebai-adsk commented on lib/mayaUsd/utils/layerLocking.cpp
> +        return MStatus::kFailure;
IDK if it should be considered failure, but as long as we don't end-up printing error in the log, it's fine.

2024-02-28 14:04 UTC, pierrebai-adsk approved these changes
LGTM

2024-02-28 16:59 UTC, merged