EMSUSD-1518 As an artist, I want the ability to determine whether a collection includes all objects by default or not
Autodesk/maya-usd pull request #3988
Opened 2024-11-06 18:13 UTC by barbalt

2024-11-07 15:14 UTC, AramAzhari-adsk commented on lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
> +    def icon(self, name: str) -> QIcon:
Is this being used somewhere?

2024-11-07 15:46 UTC, barbalt commented on lib/mayaUsd/resources/ae/usd-shared-components/src/python/usdSharedComponents/common/theme.py
> +    def icon(self, name: str) -> QIcon:
No, I can remove the icon function

2024-11-08 19:23 UTC, seando-adsk commented on lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
> +                logger.exception(ex)
Why do we need a logger? Can you just use `print` instead? Maya captures stdout for the Script Editor.

2024-11-08 19:23 UTC, seando-adsk commented on lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
> +class LightLinkingCustomControl(object):
Please place this in a separate file like all the other custom controls.

2024-11-08 19:26 UTC, seando-adsk requested changes
custom control should be a separate file.

2024-11-11 19:35 UTC, AramAzhari-adsk commented on lib/mayaUsd/resources/ae/usdschemabase/lightCustomControl.py
> +                print(ex)
Not a huge deal but could be a bit more descriptive:
`print('Failed to create Light custom control: %s' % (ex))`

2024-11-11 20:47 UTC, AramAzhari-adsk submitted a review, later dismissed

2024-11-19 15:26 UTC, seando-adsk commented on lib/mayaUsd/resources/ae/CMakeLists.txt
> +)
As agreed, we won't support this for 2022, so just wrap all this in `if(MAYA_APP_VERSION VERSION_GREATER_EQUAL 2023)`

2024-11-19 15:27 UTC, seando-adsk commented on lib/mayaUsd/resources/ae/CMakeLists.txt
> +        ${_SUBDIR}/lightCustomControl.py
Move this one to the section below and just install it only for 2023.

2024-11-19 15:32 UTC, seando-adsk commented on lib/mayaUsd/resources/ae/usdschemabase/ae_template.py
> +from .lightCustomControl import LightLinkingCustomControl
I think you could wrap this in a try/except block and set a boolean variable such as `lightLinkingSupported`. Then at line 649 below only do it when that variable is True.

2024-11-19 15:32 UTC, seando-adsk requested changes
As agreed we won't support this in 2022.

2024-11-19 22:13 UTC, AramAzhari-adsk approved these changes

2024-11-20 15:35 UTC, merged