EMSUSD-1692 - Adds LookdevXUsd Extension
Autodesk/maya-usd pull request #4040
Opened 2024-12-09 21:46 UTC by AramAzhari-adsk

This change adds USD support for LookdevX to allow compiling with different versions of USD.

2024-12-10 17:52 UTC, seando-adsk commented on plugin/adsk/plugin/CMakeLists.txt
> +)
This should be wrapped in the cmake flag. We only need to link with it when its built.

2024-12-10 17:54 UTC, seando-adsk commented on plugin/adsk/plugin/CMakeLists.txt
> +)
And you'll need to add a `target_compile_definitions` so you can use ifdef in the plugin.cpp below.

2024-12-10 17:54 UTC, seando-adsk commented on plugin/adsk/plugin/plugin.cpp
> +#include <lookdevXUsd/LookdevXUsd.h>
This line and the two calls below need to be wrapped in `#ifdef` and only compiled in when we built LookdevXUsd.

2024-12-10 17:55 UTC, seando-adsk requested changes
A couple of minor changes are required.

2024-12-10 19:34 UTC, AramAzhari-adsk commented
Currently waiting on https://github.com/Autodesk/maya-usd/pull/4042 to be integrated into the system that the clang formatting will be check against.

2024-12-10 19:46 UTC, seando-adsk commented on test/lib/ufe/CMakeLists.txt
> +            "BUILD_LOOKDEVXUSD_LIBRARY=${BUILD_LOOKDEVXUSD_LIBRARY}"
Ah yes, sorry got them reversed.

2024-12-11 11:31 UTC, frohnej-adsk submitted a review, later dismissed
LGTM

2024-12-17 20:42 UTC, seando-adsk approved these changes
Excellent work thanks

2024-12-17 21:16 UTC, merged