Remove #if/def directives for UFE_PREVIEW_VERSION_NUM >= 2021 now that PR 119 is out.
Autodesk/maya-usd pull request #802
Opened 2020-09-28 15:48 UTC by HamedSabri-adsk

Remove #if/def directives for UFE_PREVIEW_VERSION_NUM >= 2021

2020-09-28 15:57 UTC, ppt-adsk approved these changes
Thanks for doing this Hamed.

2020-09-28 17:23 UTC, ppt-adsk approved these changes

2020-09-28 20:14 UTC, seando-adsk commented on lib/mayaUsd/ufe/UsdSceneItem.h
> +	#if UFE_PREVIEW_VERSION_NUM >= 2020
Why didn't you remove this one?

2020-09-28 20:16 UTC, seando-adsk commented on lib/mayaUsd/ufe/UsdSceneItem.h
> +	#if UFE_PREVIEW_VERSION_NUM >= 2020
This should be changed into the UFE_V2 check.

2020-09-28 20:16 UTC, seando-adsk requested changes
Great job thanks. One minor comment.

2020-10-01 00:30 UTC, HamedSabri-adsk commented
@ppt-adsk @seando-adsk 

Per our offline discussion,  we are unfortunately stuck with some of these #if/#defs since we still need to support UFE 1.0. :(

For now, I changed my #if/#defs from `UFE_PREVIEW_VERSION_NUM >= 2020` to `UFE_V2_FEATURES_AVAILABLE` so at least it 
is a little bit more readable :) 

I also cleaned up some bunch of unnecessary #if/defs. Will add github comments in the PR where it is appropriate tomorrow.

See 346c6f58271a37827f7b8705d10e2e6e885bdb2f

2020-10-01 00:36 UTC, ppt-adsk approved these changes

2020-10-06 19:39 UTC, seando-adsk approved these changes

2020-10-06 23:59 UTC, merged