MAYA-107167 - Keep USDZ texture paths relative
Autodesk/maya-usd pull request #865
Opened 2020-10-23 21:17 UTC by JGamache-autodesk

If the path requires a relationship to resolves, we keep it relative.
Fixes #795

2020-10-24 00:19 UTC, mattyjams requested changes
There's a utility function available in the `Ar` library that we should use instead of the test that's there now. Otherwise, these changes make sense to me.

But I'm not seeing how this change addresses #795. That issue has to do with export, and this only deals with import. I would guess that it's the stuff here that @dgovil is talking about needing to bypass in order to see the desired asset paths in the exported package?:
https://github.com/Autodesk/maya-usd/blob/96d40b7e6c019e47902364d979b3758545631299/lib/usd/translators/shading/usdFileTextureWriter.cpp#L228

2020-10-24 00:19 UTC, mattyjams commented on lib/usd/translators/shading/usdUVTextureReader.cpp
> +                != SdfPathTokens->relationshipTargetEnd.GetString()[0]) {
We should use `Ar` here to test this instead:

```C++
#include <pxr/usd/ar/packageUtils.h>
...
        if (!filePath.empty() && !ArIsPackageRelativePath(filePath)) {
...
```

2020-10-26 13:55 UTC, JGamache-autodesk commented
I missed the "We are still using pxrUSD.bundle to do our exporting.". I will re-check and fix that code path.

2020-10-26 16:35 UTC, dgovil commented
Thanks for fixing up the pxrUSD.bundle too! We're about to transition to the mayaUSD.bundle now so hopefully I won't be an imposition on y'all for much longer in that regard, but this will be great for all our code that still calls the pixar export command instead (so hard to track down code across multiple teams and get them all ported)

2020-10-26 17:29 UTC, mattyjams approved these changes

2020-10-26 19:01 UTC, merged